### ISSUE TITLE
Radio Button Field Component

### ISSUE THREAD

**Issue by f1lander** [ObolNetwork/obol-ui#53]
## description
create radio button field component

## figma
<img width="368" alt="image" src="https://user-images.githubusercontent.com/5679878/174953497-f3018bdb-0503-4ead-91a2-3f3290e9c859.png">

https://www.figma.com/file/iXKExkvVS8K9Vc13mz3jxk/Deep-Work-x-Obol?node-id=961%3A7297

**Comment by RacketyWater7** [comment]
I intend to work on this issue.

**Comment by f1lander** [comment]
> I intend to work on this issue.

Awesome, our design system is built with stitches.dev and NextJs please refer to the https://stitches.dev documentation first 

Use git branching model flow to submit PR's, for example `ft/radio-button-component`
