### ISSUE TITLE
Correct Typos

### ISSUE THREAD

**Issue by thomasheremans** [ObolNetwork/obol-ui#67]
Found two typos while going through the docs

**Section**: Getting Started > Overview > The Network > 1st Paragraph
Replace _principals_ with _principle_

**Section**: Distributed Validators > Peer Discovery > Authenticating a distributed validator client > 3rd Paragraph
Replace _it checks if it's_ with _it checks if its_

**Comment by xenowits** [comment]
Fixed in https://github.com/ObolNetwork/obol-docs/pull/33
