### ISSUE TITLE
calculate config_hash

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/obol-ui#79]
## Problem to be solved
Currently, the API calculates the `config_hash` from the payload. The API also sets the `current_timestamp` before sending the payload to hash.

## Proposed Solution
The UI should create a payload which includes uuid, timestamp and a config_hash among other existing fields. The calculation for config_hash can be taken from https://github.com/KyneSoftware/nft-api/blob/master/src/dv/dv.hash.ts. 

Note that the API would hash the input payload to check if `calculated_hash == config_hash_from_frontend`. The API would then store the cluster into the database after performing appropriate checks and validations.

**Comment by thomasheremans** [comment]
@xenowits can you copy on the launchpad repo and close this? Thanks

**Comment by xenowits** [comment]
New one created in dv-launchpad repo: https://github.com/ObolNetwork/dv-launchpad/issues/77
