### ISSUE TITLE
Fix TeamMemberCard on Mobile

### ISSUE THREAD

**Issue by f1lander** [ObolNetwork/obol-ui#83]
TeamMemberCard on mobile are not aligned correctly when the job title is larger than usual

![image](https://user-images.githubusercontent.com/5679878/185732115-548af016-8fcd-4e36-baaa-a561573e2a9c.png)

![image](https://user-images.githubusercontent.com/5679878/185732117-a333899a-31bd-4643-88ea-010fe9e86374.png)

**Comment by thomasheremans** [comment]
@f1lander @HananINouman , this repo seem to have fallen through the cracks and not added to our project, could you please size this issue as we are working on it this sprint? I will add the action to auto-add issues to the project tracker. Thanks
